### ISSUE TITLE
Question about Setting up Virtual Environment

### ISSUE THREAD

**Issue by Dipan-Zhang** [AnyLoc/Revisit-Anything#1]
Hey dear Authors, 

thanks a lot for the nice work and open source your code. However, the instruction for setting up a virtual environment seems to be missing in the Readme file. Are you planing to add this part sometime in the near future? 

btw, I also tried to follow the `Getting Started` process in AnyLoc, but there it complains about `ModuleNotFoundError: No module named 'AnyLoc'`

Best,

**Comment by Shubodh** [comment]
Hello @Dipan-Zhang ,
Yes we plan to add more details in next 1-2 weeks and make it more elaborate.
Apologies for the delay.

**Comment by ch0x01e** [comment]
You can clone the following project into the code folder   https://github.com/AnyLoc/AnyLoc

**Comment by Shubodh** [comment]
No, it is not required. We are updating the code such that it doesn't have any AnyLoc dependency. 

@Dipan-Zhang You don't need to setup AnyLoc, we will update the code in next 2 days and then it should work fine.

**Comment by Kartikgar** [comment]
We have added the virtual environment setup instructions in the README. Sorry for the delay!
