### ISSUE TITLE
place_rec_global_any_dataset_pca_extraction.py file is missing

### ISSUE THREAD

**Issue by ch0x01e** [AnyLoc/Revisit-Anything#2]
Hello, I would like to ask where is the place_rec_global_any_dataset_pca_extraction.py file in the README
![image](https://github.com/user-attachments/assets/42619cb8-40df-494c-b62b-513b43d13211)

**Comment by Shubodh** [comment]
Hey, fixed it. The script was named incorrectly.

**Comment by Thiagor2002** [comment]
what should be the 'experiment' ?

**Comment by Shubodh** [comment]
Hello @YongDeng715 , please go through ["Running the code" section](https://github.com/AnyLoc/Revisit-Anything?tab=readme-ov-file#running-the-code) of README:

> First, set the path where you stored datasets i.e. workdir_data in place_rec_global_config.py. Also, see which experiment/dataset you want to run in place_rec_global_config.py. The default config we use in paper is exp0_global_SegLoc_VLAD_PCA_o3, i.e. nbr aggregation for order 3 with PCA. You can try out other orders with/without PCA if you'd like.
