### ISSUE TITLE
Reproduce the results

### ISSUE THREAD

**Issue by kaigelee** [AnyLoc/Revisit-Anything#4]
I would like to ask what hardware environment is needed to reproduce all the results of the paper? For example, 1*3090?

**Comment by Shubodh** [comment]
Hello @kaigelee ,
3090 should be more than sufficient to reproduce all results of the paper.
We extract SAM masks at a lower resolution (without much loss in performance) so even 12 GB vRAM should be sufficient (possibly even 8). DINOv2 should run easily at higher resolution too. 

Closing this issue. Please feel free to reopen if this doesn't solve your issue.
